from tkinter import *
m=Tk()
m.geometry('500x500')
m.configure(bg='purple')
a=Label(m,text="Python Internship")
a.pack()
e=Entry(m)
e.pack()
b=Button(m,text="Submit",bg="blue",fg="white")
b.pack()

t=Text(m,height=2,width=30)
t.pack()
t.insert(END,'Welcome To Python..')

w=Spinbox(m,from_=0,to=10)
w.pack()

v=IntVar()
bb=Radiobutton(m,text='ABC',variable=v)
bb.pack()

var1=IntVar()
cc=Checkbutton(m,text='Male',variable=var1)
cc.pack()

l1=Listbox(m)
l1.insert(1,'Hello')
l1.insert(2,'Python.....')
l1.pack()

me=Menu(m)
m.config(menu=me)
filemenu=Menu(me)
editmenu=Menu(me)
me.add_cascade(label='File',menu=filemenu)
me.add_cascade(label='Edit',menu=editmenu)
filemenu.add_command(label='New')
filemenu.add_command(label='Open')
filemenu.add_command(label='Save')
filemenu.add_command(label='Save As')
editmenu.add_command(label='Cut')
editmenu.add_command(label='Copy')
editmenu.add_command(label='Paste')
editmenu.add_command(label='Undo')
m.mainloop()
